### ISSUE TITLE
Feature request: Support IPinfo IP to Country ASN database

### ISSUE THREAD

**Issue by abdullahdevrel** [brimdata/geoip-conn#46]
I am requesting to add support for [IPinfo's IP to Country database](https://ipinfo.io/products/free-ip-database) to the project. The database has the following features:

- It includes country and ASN information in the same database.
- It is updated daily, with zero compromise to accuracy. There is no range clustering, and the database provides full accuracy.
- The data granularity reaches `/32` level.
- The database comes in MMDB database format.

## Database schema

| Field Name       | Example                      | Data Type | Description                                       |
|------------------|------------------------------|-----------|---------------------------------------------------|
| `start_ip`       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| `end_ip`         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| `country`        | JP                           | TEXT      | ISO 3166 country code of the location             |
| `country_name`   | Japan                        | TEXT      | Name of the country                               |
| `continent`      | AS                           | TEXT      | Continent code of the country                     |
| `continent_name` | Asia                         | TEXT      | Name of the continent                             |
| `asn`            | AS2519                       | TEXT      | Autonomous System Number                          |
| `as_name`        | ARTERIA Networks Corporation | TEXT      | Name of the AS (Autonomous System) organization   |
| `as_domain`      | arteria-net.com              | TEXT      | Official domain or website of the AS organization |

Samples are available here: https://github.com/ipinfo/sample-database/tree/main/IP%20to%20Country%20ASN

## Usage

The database is available for free to download by opening a [free IPinfo account](https://ipinfo.io/signup). The database is licensed under CC-BY-SA 4.0, which permits commercial usage through providing attribution and can be integrated directly into the project. The database can be downloaded simply by accessing the [storage URI with an access token](https://ipinfo.io/developers/database-filename-reference).

```bash
curl -L https://ipinfo.io/data/free/country_asn.mmdb?token=<YOUR_TOKEN> -o country_asn.mmdb
```

## Additional context

Supporting [IPinfo's IP to Country ASN database](https://ipinfo.io/developers/ip-to-country-asn-database) will resolve this issue as well: https://github.com/brimdata/geoip-conn/issues/39

---

Please let me know if you have any feedback.

**Comment by abdullahdevrel** [comment]
Hi @philrz, were you able to review my request? I am looking forward to hearing from you. Thanks!

**Comment by philrz** [comment]
@abdullahdevrel: I did see this issue as it arrived and also your email, so thanks for that. The priorities of the team at Brim Data has recently been less network-centric than in the past which is why we've not been able to spend time on this yet. I'll spend some time looking closer at it as soon as I can and will update here when that happens.

**Comment by abdullahdevrel** [comment]
Thank you very much, @philrz. No worries. Please, there is no rush. Really appreciate your reviewing the ticket.

**Comment by philrz** [comment]
Hello again @abdullahdevrel. I had a chance to look closer at this. Unfortunately I think there needs to be some development at the Zeek layer before this geoip-conn package can leverage a different geolocation database. I'm really not much of a developer myself, and I was only able to put together this modest package because the Zeek scripting is pretty minimal and I was able to repeat the pattern of a [previous package](https://github.com/zeek/bro-scripts/blob/master/conn-add-geodata.bro). But based on what I can find, it looks like the [Zeek geolocation docs](https://docs.zeek.org/en/master/customizations.html#address-geolocation-and-as-lookups) set expectations that Zeek is only expected to work specifically with MaxMind's databases. Looking at their [MMDB.cc](https://github.com/zeek/zeek/blob/master/src/MMDB.cc) code it does look like they're wired up to look for data using field names that are specific to MaxMind's schema. In other words, while it's surely handy that your databases are in MMDB format, that alone may not be sufficient.

Just to be sure, I did try swapping in the IPinfo `country_asn.mmdb` in place of the `GeoLite2-City.mmdb` that this package currently uses and tried processing a sample pcap. Zeek didn't have any complaints about the database format, but it also didn't add any of the geolocation data to the `conn` records.

With that, I'll need to flip this issue back in your direction and pose it as a challenge. If you can manage to enhance Zeek to make use of the IPinfo databases (e.g., get a PR merged into the [Zeek repo](https://github.com/zeek/zeek) that allows Zeek's BIFs like `lookup_location()` and `lookup_autonomous_system()` to successfully retrieve values when an IPinfo database is in place instead of MaxMind) then I think this geoip-conn package would "just work" with the IPinfo data. If for some reason you get that far and geoip-conn still needs some further enhancement, I'd be happy to pick up the effort from there.

**Comment by abdullahdevrel** [comment]
Hey @philrz, thank you very much for looking into the issue and providing a detailed guideline on how to add our bring our data to Zeek. I really appreciate it. I will close the request for now. If I make some progress with the Zeek project, I will let you know. Again, thank you very much.
